### ISSUE TITLE
QQ账号登录时需要验证，如何解决？

### ISSUE THREAD

**Issue by skyls03** [FlyRenxing/RenxingPush#1]
如题

**Comment by FlyRenxing** [comment]
可以根据控制台提示进行操作，验证一到两次后不改变环境的情况下以后就不会再出现认证了。
附 [机器人登录文档](https://docs.mirai.mamoe.net/Bots.html#_2-登录)

**Comment by skyls03** [comment]
@FlyRenxing  感谢帮助
