### ISSUE TITLE
jar包启动报错

### ISSUE THREAD

**Issue by M-qy** [FlyRenxing/RenxingPush#18]
小白求助！修改了application.yml，然后用Dockerfile里的命令"java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /root/app.jar"启动之后报“getConnection but jdbcUrl is not set,jdbcUrl=null,username=null”的错误，是还要传参嘛？
![image](https://github.com/user-attachments/assets/48718881-7614-4c1b-847f-b9e506faaf57)

**Comment by FlyRenxing** [comment]
可能是配置文件有问题，可以在https://github.com/FlyRenxing/RenxingPush/releases/tag/v1.0.0 下载jar包并获取yml示例配置

**Comment by M-qy** [comment]
那个配置文件是不是改datasource里的配置就好了？我也改了，但是还是一样的错误
![image](https://github.com/user-attachments/assets/c1f3b761-f09d-414b-8d60-383606816718)
![image](https://github.com/user-attachments/assets/f18dcb3d-a38c-4aab-bbbe-5eddecbd5fca)

**Comment by FlyRenxing** [comment]
根据你提供的配置，似乎没有什么问题..不如先尝试直接在本机java -jar启动排除docker可能的影响

**Comment by M-qy** [comment]
找到原因了，需要写个working_dir: /root，不过我搭建好后又遇到一个报错，这个报错在post请求后就出现，是什么原因呢？对8000端口请求没错吧？顺便也问一下api那个cipher是websocket的token吗？
![image](https://github.com/user-attachments/assets/2a895af9-9ebf-4490-9150-ef49d12757bc)

**Comment by FlyRenxing** [comment]
cipher是用户类里的属性，可以理解为认证token
先调用用户注册，应该会自动为这个用户生成一个cipher
图中报错应该也是cipher不对的原因

**Comment by M-qy** [comment]
额额，大佬，/user/login是用什么用户密码登录？
![image](https://github.com/user-attachments/assets/4370330e-4b66-49e9-9b9a-4ac78dafbbf9)

**Comment by M-qy** [comment]
大佬，那个每日最大发送次数能设置无限吗

**Comment by M-qy** [comment]
cipher会变动吗，还是注册了就不变了？

**Comment by FlyRenxing** [comment]
注册了就不变了，除非调用重置接口




Renxing
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FlyRenxing/RenxingPush"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月24日(星期二) 中午11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FlyRenxing/RenxingPush] jar包启动报错 (Issue #18)





 
cipher会变动吗，还是注册了就不变了？

**Comment by FlyRenxing** [comment]
这个要手动改下数据库的user表里的字段，似乎没做成接口




Renxing
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FlyRenxing/RenxingPush"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月24日(星期二) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FlyRenxing/RenxingPush] jar包启动报错 (Issue #18)





 
大佬，那个每日最大发送次数能设置无限吗

**Comment by FlyRenxing** [comment]
先调用用户注册接口




Renxing
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FlyRenxing/RenxingPush"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月24日(星期二) 上午10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FlyRenxing/RenxingPush] jar包启动报错 (Issue #18)





 
额额，大佬，/user/login是用什么用户密码登录？
 image.png (view on web)

**Comment by M-qy** [comment]
无限是设置为-1吗？我现在主要的接口试了一下，感觉好像有泄露危险，最好全都在内网请求

**Comment by FlyRenxing** [comment]
管理接口好像都有管理员登陆权限保护，没有-1的选项，欢迎pr..
